---
- name: Windows Management Playbook
  hosts: windows
  gather_facts: no
  tasks:

    - name: Ping Windows host
      win_ping:
      tags: [ping]

   
    - name: Install IIS Web-Server
      win_feature:
        name: Web-Server
        state: present
      tags: [install_iis]

    
    - name: Create test user
      win_user:
        name: testuser
        password: "MyP@ssw0rd!"
        state: present
        groups:
          - Users
      tags: [user]

    - name: Create demo directory
      win_file:
        path: C:\ansible_demo
        state: directory
      tags: [files]

    - name: Copy hello.txt file
      win_copy:
        src: ./hello.txt
        dest: C:\ansible_demo\hello.txt
      tags: [files]

    
    - name: Run PowerShell to get processes
      win_shell: Get-Process | Select-Object -First 5
      register: ps_output
      tags: [powershell]

    - name: Show PowerShell output
      debug:
        var: ps_output.stdout
      tags: [powershell]

  
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
      tags: [choco]

    - name: Install Git using Chocolatey
      win_chocolatey:
        name: git
        state: present
      tags: [choco]

    
    - name: Ensure IIS service is started
      win_service:
        name: W3SVC
        start_mode: auto
        state: started
      tags: [service]

   
    - name: Install critical & security updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      tags: [updates]

    
    - name: Set custom registry key
      win_regedit:
        path: HKLM:\Software\AnsibleDemo
        name: DemoValue
        data: "Hello from Ansible"
        type: string
      tags: [registry]

  
    - name: Reboot Windows host
      win_reboot:
        msg: "Rebooting after updates"
        timeout: 600
      tags: [reboot]
