cat cpu_alert.yml 
---
- name: CPU Alert Response
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Print CPU alert message
      debug:
        msg: "High CPU usage detected! Taking action..."

    - name: Kill stress process if running
      ansible.builtin.shell: |
        if pgrep stress; then
          pkill stress
        fi
      failed_when: false

    - name: Log high CPU alert to persistent file
      ansible.builtin.shell: "echo '⚡High CPU usage detected! Event received.' >> /home/arun/cpu_alert.txt"
